version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-validator-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - phone-validator-network
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: phone-validator-nginx
    restart: unless-stopped
    ports:
      - "8200:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - phone-validator-network
    depends_on:
      - app

  redis:
    image: redis:7-alpine
    container_name: phone-validator-redis
    restart: unless-stopped
    ports:
      - "6377:6379"
    networks:
      - phone-validator-network
    volumes:
      - redis-data:/data

networks:
  phone-validator-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
